In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
df = pd.read_csv('labeled.csv')
df.head()

comment  toxic
0               Верблюдов-то за что? Дебилы, бл...\n    1.0
1  Хохлы, это отдушина затюканого россиянина, мол...    1.0
2                          Собаке - собачья смерть\n    1.0
3  Страницу обнови, дебил. Это тоже не оскорблени...    1.0
4  тебя не убедил 6-страничный пдф в том, что Скр...    1.0

In [5]:
#using the count vectorizer
X = df['comment']
count = CountVectorizer()
word_count=count.fit_transform(X)
print(word_count)

  (0, 7474)	1
  (0, 59887)	1
  (0, 17206)	1
  (0, 66317)	1
  (0, 13525)	1
  (0, 5534)	1
  (1, 65040)	1
  (1, 67953)	1
  (1, 36839)	1
  (1, 19208)	1
  (1, 51794)	1
  (1, 29347)	1
  (1, 9067)	1
  (1, 65005)	2
  (1, 16589)	1
  (1, 65279)	1
  (1, 16551)	1
  (1, 6684)	2
  (1, 31914)	1
  (1, 6755)	1
  (1, 22818)	1
  (1, 21603)	1
  (1, 45908)	1
  (2, 55308)	1
  (2, 55320)	1
  :	:
  (14411, 43651)	1
  (14411, 14653)	1
  (14411, 35598)	1
  (14411, 23224)	1
  (14411, 24011)	1
  (14411, 7955)	1
  (14411, 54056)	1
  (14411, 58932)	1
  (14411, 22005)	1
  (14411, 7314)	1
  (14411, 44569)	1
  (14411, 53085)	1
  (14411, 30457)	1
  (14411, 50852)	1
  (14411, 44589)	1
  (14411, 40174)	1
  (14411, 39501)	1
  (14411, 36038)	1
  (14411, 22474)	1
  (14411, 67205)	1
  (14411, 52893)	1
  (14411, 65089)	1
  (14411, 65147)	1
  (14411, 7509)	1
  (14411, 12085)	1


In [6]:
print(word_count.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True)
tfidf_transformer.fit(word_count)
df_idf = pd.DataFrame(tfidf_transformer.idf_, index=count.get_feature_names_out(),columns=["idf_weights"])

In [9]:
#inverse document frequency
df_idf.sort_values(by=['idf_weights'])

idf_weights
не                1.860826
на                2.169848
что               2.295682
это               2.575201
то                2.639941
...                    ...
маршрутах         9.882739
маршрутизатор     9.882739
маршрутизации     9.882739
мартышкой         9.882739
ётавских          9.882739

[68423 rows x 1 columns]

In [12]:
#tfidf
tf_idf_vector=tfidf_transformer.transform(word_count)
feature_names = count.get_feature_names_out()
first_document_vector=tf_idf_vector[1]
df_tfifd= pd.DataFrame(first_document_vector.T.todense(), index=feature_names, columns=["tfidf"])
df_tfifd.sort_values(by=["tfidf"],ascending=False)

tfidf
хохлов       0.402224
россиянина   0.331758
отдушина     0.331758
затюканого   0.331758
кисель       0.331758
...               ...
киселем      0.000000
киселя       0.000000
киселёва     0.000000
кислводская  0.000000
ётавских     0.000000

[68423 rows x 1 columns]